// vuex-todo/src/components/TodoForm.vue
<template>
  <div>
    <input type="text" :value="val" @input="handleInput" />
    <button @click="add">提交</button>
  </div>
</template>

<script>
import { mapActions } from "vuex";
export default {
  name: "todoform",
  computed: {
    val() {
      return this.$store.state.val;
    }
  },
  methods: {
    ...mapActions(["addTodo"]),
    add() {
      if (this.val.trim()) {
        this.addTodo({
          newTodo: { text: this.val, completed: false }
        });
      } else {
        alert("hahahahahah");
      }
    },

    handleInput() {
      // console.log(event.target.value);
      // 获取输入的内容用来触发 mutation
      this.$store.commit("changeVal", event.target.value);
    }
  }
};
</script>

<style>
</style>

// react-todo/src/components/TodoForm.js
import React, { Component } from "react"
class TodoForm extends Component {
  state = {
    text: ""
  }
  handleInput = e => {
    this.setState({
      text: e.target.value
    })
  }
  add = e => {
    // 获取按下的是键盘上哪一个钮
    // console.log(e.which)
    // console.log(e.key)
    // console.log(e.keyCode)
    if (e.keyCode === 13) {
      this.props.add(this.state.text)
    }
  }
  render() {
    // 如何绑定键盘事件
    return (
      <div>
        <input
          onChange={this.handleInput}
          type='text'
          value={this.state.text}
          onKeyDown={this.add}
        />
        <button onClick={() => this.props.add(this.state.text)}>提交</button>
      </div>
    )
  }
}
export default TodoForm
