// vuex-todo/src/components/TodoFoot.vue
<template>
  <div>
    <span>{{$store.getters.activeNum}} item left</span>
    <div>
      <button @click="changeType('all')" :class=" type==='all' ?'active' : ''">all</button>
      <button @click="changeType('active')" :class=" type==='active' ?'active' : ''">active</button>
      <button @click="changeType('completed')" :class=" type==='completed' ?'active' : ''">completed</button>
    </div>
  </div>
</template>

<script>
import { mapState, mapMutations } from "vuex";
export default {
  name: "todofoot",
  computed: {
    ...mapState({
      type: state => state.filter.type
    })
  },
  methods: {
    ...mapMutations(["changeType"])
  }
};
</script>

<style>
.active {
  background-color: red;
}
</style>

// react-todo/src/components/TodoFoot.js
// 该组件没有自己的state
// 一般写成无状态组件(函数式组件) 只用来做展示用
import React from "react"
const TodoFoot = props => {
  return (
    <div>
      <span>
        {props.activeNum} item{props.activeNum === 1 ? "" : "s"} left
      </span>
      <button onClick={() => props.changeType("all")}>all</button>
      <button onClick={() => props.changeType("active")}>active</button>
      <button onClick={() => props.changeType("completed")}>completed</button>
    </div>
  )
}
export default TodoFoot
