// react-redux-cart/src/App.js
import React from "react"
import ProductListContainer from "./components/ProductListContainer"
import CartContainer from "./components/CartContainer"

function App() {
  return (
    <div className='App'>
      <h1>hello redux cart</h1>
      <ProductListContainer />
      <hr />
      <br />
      <CartContainer />
    </div>
  )
}
export default App

// vuex-cart/src/App.vue
<template>
  <div>
    <h1>vuex shopping cart</h1>
    <hr />
    <Products />
    <hr />
    <ShoppingCart />
  </div>
</template>

<script>
import Products from "./components/Products";
import ShoppingCart from "./components/ShoppingCart";
export default {
  name: "app",
  components: {
    Products,
    ShoppingCart
  }
};
</script>

<style>
</style>
