// react-topics/src/components/Topic.js
import React, { Component } from "react"
import axios from "axios"

// function MyComponent() {
//   return <div dangerouslySetInnerHTML={{__html: 'First &middot; Second'}} />;
// }
class Topic extends Component {
  state = {
    topic: null
  }
  componentDidMount() {
    const { id } = this.props.match.params
    axios.get(`http://localhost:3008/topics/${id}`).then(res => {
      this.setState({
        topic: res.data
      })
    })
  }
  render() {
    const { topic } = this.state
    const content = topic ? (
      <div>
        <h2>{topic.title}</h2>
        <div dangerouslySetInnerHTML={{ __html: topic.content }} />
      </div>
    ) : (
      <div>请稍等</div>
    )
    return content
  }
}
export default Topic

// vue-juejin/src/components/Topic.vue
<template>
  <div>文章展示</div>
</template>

<script>
// 如果在这个组件出现的时候获取页面地址上的 id 值
// 根据这个 id 去后台获取对应的文章信息展示到组件上
import axios from "axios";
export default {
  name: "topic",
  data() {
    return {
      topic: {}
    };
  },
  created() {
    // 获取动态参数
    const { id } = this.$route.params;
    axios.get(`http://localhost:3008/topics/${id}`).then(res => {
      console.log(res.data);
    });
  }
};
</script>

<style>
</style>
