// vuex-post/src/components/PostComment.vue
<template>
  <div>
    <span>评论</span>
    <ul v-if="comments.length">
      <li v-for="comment in comments" :key="comment.id">{{comment.text}}</li>
    </ul>
    <input type="text" v-model="val" />
    <button @click="addComment">添加评论</button>
  </div>
</template>

<script>
import axios from "axios";
export default {
  name: "postcomment",
  data() {
    return {
      val: ""
    };
  },
  created() {
    // 发请求更新 store 内的 comments 数据
    const { id } = this.$route.params;
    this.$store.dispatch("getComments", { id });
  },
  computed: {
    comments() {
      return this.$store.state.comments;
    }
  },
  methods: {
    addComment() {
      // 获取输入框的内容 发送请求更新后台数据 再更新本地的 store 数据
      const { id } = this.$route.params;
      this.$store.dispatch("addComment", {
        val: this.val,
        id,
        clearInput: this.clearInput
      });
    },
    clearInput() {
      this.val = "";
    }
  }
};
</script>

<style>
</style>

// react-redux-post/src/components/PostComment.js
import React, { Component } from "react"
import Axios from "axios"
import store from "../store"
class PostComment extends Component {
  state = {
    val: ""
  }
  addComment = () => {
    // 1. 发送请求添加远端的评论
    // 2. 将网上更新好的在本地展示
    const { val } = this.state
    if (val.trim()) {
      Axios.post("http://localhost:3008/comments", {
        text: val,
        postId: this.props.postId
      }).then(res => {
        store.dispatch({ type: "ADDCOMMENT", newComment: res.data })
        this.setState({
          val: ""
        })
      })
    }
  }
  render() {
    const { comments } = this.props
    const commentList = comments.length ? (
      <ul>
        {comments.map(comment => (
          <li key={comment.id}>{comment.text}</li>
        ))}
      </ul>
    ) : (
      "请稍等。。。"
    )
    return (
      <div>
        <h4>评论</h4>
        {commentList}
        <textarea
          value={this.state.val}
          onChange={event =>
            this.setState({
              val: event.target.value
            })
          }
        />
        <button onClick={this.addComment}>添加评论</button>
      </div>
    )
  }
}
export default PostComment
