// vuex-post/src/components/PostBody.vue
<template>
  <div v-if="post">
    <h2>{{post.title}}</h2>
    <span>评论数:{{commentNum}}</span>
    <p>{{post.content}}</p>
  </div>
</template>

<script>
export default {
  name: "postbody",
  computed: {
    post() {
      const { id } = this.$route.params;
      console.log(this.$store.state.posts);
      return this.$store.state.posts.find(post => post.id === id);
    },
    commentNum() {
      return this.$store.state.comments.length;
    }
  }
};
</script>

<style>
</style>

// react-redux-post/src/components/PostBody.js
import React from "react"
const PostBody = props => {
  const { post, comments } = props
  return props.post ? (
    <div>
      <h1>{post.title}</h1>
      <span>评论数:{comments.length}</span>
      <div dangerouslySetInnerHTML={{ __html: post.content }} />
    </div>
  ) : (
    <div>稍等。。。</div>
  )
}
export default PostBody
